Repository elastic-infra/terraform-modules, pull requests merged in 2021-11, with the labels that each got.

#39 Output list of IAM policies attached to the base instance profile
  aws/ei-base-role/README.md
  aws/ei-base-role/output.tf
Labels: size/S

#40 enable to switch VPCe service_name per region
  aws/ei-privatelink-consumer/README.md
  aws/ei-privatelink-consumer/main.tf
  aws/ei-privatelink-consumer/variables.tf
Labels: size/S

#41 Topic/apply for Inter-region peering
  aws/ei-privatelink-consumer/README.md
  aws/ei-privatelink-consumer/main.tf
  aws/ei-privatelink-consumer/variables.tf
Labels: size/M

#42 Add mfa_delete option
  aws/private-s3-bucket/README.md
  aws/private-s3-bucket/main.tf
  aws/private-s3-bucket/variables.tf
Labels: size/XS

#43 Support object_lock_configuration
  aws/private-s3-bucket/README.md
  aws/private-s3-bucket/main.tf
  aws/private-s3-bucket/variables.tf
Labels: size/M
