Repository elastic-infra/terraform-modules, pull requests merged in 2021-01, with the labels that each got.

#22 support terraform v0.14
  aws/ei-base-role/versions.tf
  aws/private-s3-bucket/constraints.tf
Labels: size/XS

#23 Fix/validation of lb-accesslog-table
  aws/alb-accesslog-table/README.md
  aws/alb-accesslog-table/variables.tf
  aws/nlb-accesslog-table/README.md
  aws/nlb-accesslog-table/variables.tf
Labels: size/S

#24 Add Athena table for WAF
  aws/waf-log-table/README.md
  aws/waf-log-table/constraints.tf
  aws/waf-log-table/main.tf
  aws/waf-log-table/variables.tf
Labels: size/L
