Repository elastic-infra/terraform-modules, pull requests merged in 2022-12, with the labels that each got.

#63 `private-s3-bucket` module support aws_s3_bucket_ownership_controls & set BucketOwnerEnforced by default
  aws/private-s3-bucket/README.md
  aws/private-s3-bucket/bucket_options.tf
  aws/private-s3-bucket/main.tf
  aws/private-s3-bucket/variables.tf
Labels: size/S

#64 loosen constraints of ei-base-role to use terraform 1.3.0 or later
  aws/ei-base-role/versions.tf
Labels: size/XS

#65 private-s3-bucket enable SSE−S3 by default
  aws/private-s3-bucket/README.md
  aws/private-s3-bucket/bucket_options.tf
  aws/private-s3-bucket/main.tf
  aws/private-s3-bucket/variables.tf
Labels: size/M
