Repository elastic-infra/terraform-modules, pull requests merged in 2022-01, with the labels that each got.

#45 Add scheduler for redash v10
  aws/redash/README.md
  aws/redash/container_definitions.tf
  aws/redash/ecs.tf
  aws/redash/local_variables.tf
  aws/redash/main.tf
  aws/redash/variables.tf
Labels: size/M

#46 Remove unused variable `scheduler_desired_count`
  aws/redash/README.md
  aws/redash/variables.tf
Labels: size/XS

#49 Constraints for terraform 1.1.X
  aws/ei-base-role/README.md
  aws/ei-base-role/versions.tf
  aws/iam-service-role/README.md
  aws/iam-service-role/versions.tf
  aws/private-s3-bucket/README.md
  aws/private-s3-bucket/constraints.tf
  aws/private-s3-bucket/main.tf
  aws/redash/README.md
  aws/redash/versions.tf
  aws/tools/Makefile
Labels: size/S
