Repository elastic-infra/terraform-modules, pull requests merged in 2023-05, with the labels that each got.

#68 Move to cloudposse/label/null
  aws/vpc-peering-accepter-multiaccount/README.md
  aws/vpc-peering-accepter-multiaccount/accepter.tf
  aws/vpc-peering-requester-multiaccount/README.md
  aws/vpc-peering-requester-multiaccount/requester.tf
Labels: size/S

#69 Add ap-southeast-1 VPCe Service Name
  aws/ei-privatelink-consumer/main.tf
Labels: size/XS

#70 null-label: overwrite regex_replace_chars
  aws/vpc-peering-accepter-multiaccount/accepter.tf
  aws/vpc-peering-requester-multiaccount/requester.tf
Labels: size/S

#71 Support newer_noncurrent_versions
  aws/private-s3-bucket/README.md
  aws/private-s3-bucket/bucket_options.tf
  aws/private-s3-bucket/constraints.tf
  aws/private-s3-bucket/main.tf
  aws/private-s3-bucket/variables.tf
Labels: size/M
