Repository elastic-infra/terraform-modules, pull requests merged in 2025-02, with the labels that each got.

#97 Bastion timer
  aws/fargate-bastion/README.md
  aws/fargate-bastion/ecs.tf
  aws/fargate-bastion/variables.tf
Labels: size/S

#98 Support force_destroy
  aws/private-s3-bucket/README.md
  aws/private-s3-bucket/main.tf
  aws/private-s3-bucket/variables.tf
Labels: size/XS

#99 Tags for redash
  aws/redash/README.md
  aws/redash/cloudwatch_logs.tf
  aws/redash/ecs.tf
  aws/redash/lb.tf
  aws/redash/variables.tf
Labels: size/M
